// Generated by https://quicktype.io

export interface DotaItem {
  blink: ArcaneBoots;
  overwhelming_blink: LivingstoneSouthernWhiteFacedOwl;
  swift_blink: AeonDisk;
  arcane_blink: AeonDisk;
  recipe_arcane_blink: TartuGecko;
  recipe_swift_blink: TartuGecko;
  recipe_overwhelming_blink: TartuGecko;
  blades_of_attack: TartuGecko;
  broadsword: TartuGecko;
  chainmail: TartuGecko;
  claymore: TartuGecko;
  helm_of_iron_will: TartuGecko;
  javelin: TartuGecko;
  mithril_hammer: TartuGecko;
  platemail: TartuGecko;
  quarterstaff: TartuGecko;
  quelling_blade: LivingstoneSouthernWhiteFacedOwl;
  faerie_fire: LivingstoneSouthernWhiteFacedOwl;
  infused_raindrop: LivingstoneSouthernWhiteFacedOwl;
  wind_lace: TartuGecko;
  ring_of_protection: TartuGecko;
  stout_shield: TartuGecko;
  moon_shard: TartuGecko;
  gauntlets: TartuGecko;
  slippers: TartuGecko;
  mantle: TartuGecko;
  branches: TartuGecko;
  belt_of_strength: TartuGecko;
  boots_of_elves: TartuGecko;
  robe: TartuGecko;
  circlet: TartuGecko;
  crown: TartuGecko;
  ogre_axe: TartuGecko;
  blade_of_alacrity: TartuGecko;
  staff_of_wizardry: TartuGecko;
  ultimate_orb: TartuGecko;
  gloves: TartuGecko;
  blitz_knuckles: TartuGecko;
  lifesteal: TartuGecko;
  voodoo_mask: TartuGecko;
  ring_of_regen: TartuGecko;
  ring_of_tarrasque: TartuGecko;
  sobi_mask: TartuGecko;
  boots: TartuGecko;
  gem: LivingstoneSouthernWhiteFacedOwl;
  cloak: TartuGecko;
  talisman_of_evasion: TartuGecko;
  cheese: LivingstoneSouthernWhiteFacedOwl;
  magic_stick: LivingstoneSouthernWhiteFacedOwl;
  recipe_magic_wand: TartuGecko;
  magic_wand: LivingstoneSouthernWhiteFacedOwl;
  ghost: LivingstoneSouthernWhiteFacedOwl;
  clarity: Bottle;
  enchanted_mango: Bottle;
  flask: Bottle;
  dust: LivingstoneSouthernWhiteFacedOwl;
  bottle: Bottle;
  ward_observer: LivingstoneSouthernWhiteFacedOwl;
  ward_sentry: LivingstoneSouthernWhiteFacedOwl;
  ward_dispenser: TartuGecko;
  tango: Bottle;
  tango_single: Bottle;
  courier: TartuGecko;
  flying_courier: TartuGecko;
  tpscroll: RefresherShard;
  recipe_travel_boots: TartuGecko;
  travel_boots: TartuGecko;
  travel_boots_2: TartuGecko;
  phase_boots: LivingstoneSouthernWhiteFacedOwl;
  demon_edge: TartuGecko;
  eagle: TartuGecko;
  reaver: TartuGecko;
  relic: TartuGecko;
  hyperstone: TartuGecko;
  ring_of_health: TartuGecko;
  void_stone: TartuGecko;
  mystic_staff: TartuGecko;
  energy_booster: TartuGecko;
  point_booster: TartuGecko;
  vitality_booster: TartuGecko;
  fluffy_hat: TartuGecko;
  power_treads: TartuGecko;
  grandmasters_glaive: TartuGecko;
  recipe_hand_of_midas: TartuGecko;
  hand_of_midas: LivingstoneSouthernWhiteFacedOwl;
  oblivion_staff: TartuGecko;
  recipe_witch_blade: TartuGecko;
  witch_blade: LivingstoneSouthernWhiteFacedOwl;
  pers: TartuGecko;
  poor_mans_shield: TartuGecko;
  satchel: TartuGecko;
  recipe_bracer: TartuGecko;
  bracer: TartuGecko;
  recipe_wraith_band: TartuGecko;
  wraith_band: TartuGecko;
  recipe_null_talisman: TartuGecko;
  null_talisman: TartuGecko;
  recipe_mekansm: TartuGecko;
  mekansm: PuneHedgehog;
  recipe_vladmir: TartuGecko;
  vladmir: TartuGecko;
  recipe_wraith_pact: TartuGecko;
  wraith_pact: PuneHedgehog;
  recipe_buckler: TartuGecko;
  buckler: TartuGecko;
  recipe_ring_of_basilius: TartuGecko;
  ring_of_basilius: TartuGecko;
  recipe_holy_locket: TartuGecko;
  holy_locket: LivingstoneSouthernWhiteFacedOwl;
  recipe_pipe: TartuGecko;
  pipe: PuneHedgehog;
  recipe_urn_of_shadows: TartuGecko;
  urn_of_shadows: AeonDisk;
  recipe_headdress: TartuGecko;
  headdress: TartuGecko;
  sheepstick: PuneHedgehog;
  recipe_orchid: TartuGecko;
  orchid: PuneHedgehog;
  recipe_bloodthorn: TartuGecko;
  bloodthorn: PuneHedgehog;
  echo_sabre: ArcaneBoots;
  recipe_cyclone: TartuGecko;
  cyclone: PuneHedgehog;
  recipe_wind_waker: TartuGecko;
  wind_waker: PuneHedgehog;
  recipe_aether_lens: TartuGecko;
  aether_lens: TartuGecko;
  recipe_force_staff: TartuGecko;
  force_staff: PuneHedgehog;
  recipe_hurricane_pike: TartuGecko;
  hurricane_pike: PuneHedgehog;
  recipe_dagon: TartuGecko;
  dagon: Dagon;
  dagon_2: Dagon;
  dagon_3: Dagon;
  dagon_4: Dagon;
  dagon_5: Dagon;
  recipe_necronomicon: TartuGecko;
  necronomicon: PuneHedgehog;
  necronomicon_2: PuneHedgehog;
  necronomicon_3: PuneHedgehog;
  ultimate_scepter: TartuGecko;
  recipe_ultimate_scepter_2: TartuGecko;
  ultimate_scepter_2: TartuGecko;
  ultimate_scepter_roshan: TartuGecko;
  aghanims_shard: TartuGecko;
  aghanims_shard_roshan: TartuGecko;
  recipe_refresher: TartuGecko;
  refresher: PuneHedgehog;
  recipe_assault: TartuGecko;
  assault: TartuGecko;
  recipe_heart: TartuGecko;
  heart: TartuGecko;
  recipe_black_king_bar: TartuGecko;
  black_king_bar: PuneHedgehog;
  aegis: TartuGecko;
  recipe_shivas_guard: TartuGecko;
  shivas_guard: PuneHedgehog;
  recipe_bloodstone: TartuGecko;
  bloodstone: ArcaneBoots;
  recipe_sphere: TartuGecko;
  sphere: AeonDisk;
  lotus_orb: PuneHedgehog;
  recipe_meteor_hammer: TartuGecko;
  meteor_hammer: PuneHedgehog;
  nullifier: LivingstoneSouthernWhiteFacedOwl;
  recipe_aeon_disk: TartuGecko;
  aeon_disk: AeonDisk;
  recipe_kaya: TartuGecko;
  kaya: TartuGecko;
  trident: TartuGecko;
  combo_breaker: TartuGecko;
  refresher_shard: RefresherShard;
  recipe_spirit_vessel: TartuGecko;
  spirit_vessel: AeonDisk;
  vanguard: TartuGecko;
  recipe_crimson_guard: TartuGecko;
  crimson_guard: ArcaneBoots;
  recipe_blade_mail: TartuGecko;
  blade_mail: PuneHedgehog;
  soul_booster: TartuGecko;
  recipe_hood_of_defiance: TartuGecko;
  hood_of_defiance: PuneHedgehog;
  recipe_eternal_shroud: TartuGecko;
  eternal_shroud: PuneHedgehog;
  rapier: TartuGecko;
  recipe_monkey_king_bar: TartuGecko;
  monkey_king_bar: TartuGecko;
  radiance: TartuGecko;
  butterfly: TartuGecko;
  recipe_greater_crit: TartuGecko;
  greater_crit: TartuGecko;
  recipe_basher: TartuGecko;
  basher: ArcaneBoots;
  bfury: ArcaneBoots;
  recipe_manta: TartuGecko;
  manta: PuneHedgehog;
  recipe_lesser_crit: TartuGecko;
  lesser_crit: TartuGecko;
  recipe_dragon_lance: TartuGecko;
  dragon_lance: TartuGecko;
  recipe_armlet: TartuGecko;
  armlet: TartuGecko;
  invis_sword: PuneHedgehog;
  recipe_silver_edge: TartuGecko;
  silver_edge: PuneHedgehog;
  sange_and_yasha: TartuGecko;
  kaya_and_sange: TartuGecko;
  yasha_and_kaya: TartuGecko;
  satanic: LivingstoneSouthernWhiteFacedOwl;
  recipe_mjollnir: TartuGecko;
  mjollnir: PuneHedgehog;
  skadi: TartuGecko;
  recipe_sange: TartuGecko;
  sange: TartuGecko;
  recipe_helm_of_the_dominator: TartuGecko;
  helm_of_the_dominator: LivingstoneSouthernWhiteFacedOwl;
  recipe_helm_of_the_overlord: TartuGecko;
  helm_of_the_overlord: LivingstoneSouthernWhiteFacedOwl;
  maelstrom: TartuGecko;
  recipe_gungir: TartuGecko;
  gungir: PuneHedgehog;
  desolator: TartuGecko;
  recipe_yasha: TartuGecko;
  yasha: TartuGecko;
  mask_of_madness: PuneHedgehog;
  recipe_diffusal_blade: TartuGecko;
  diffusal_blade: AeonDisk;
  recipe_ethereal_blade: TartuGecko;
  ethereal_blade: PuneHedgehog;
  recipe_soul_ring: TartuGecko;
  soul_ring: LivingstoneSouthernWhiteFacedOwl;
  arcane_boots: ArcaneBoots;
  octarine_core: TartuGecko;
  orb_of_venom: TartuGecko;
  blight_stone: TartuGecko;
  recipe_orb_of_corrosion: TartuGecko;
  orb_of_corrosion: TartuGecko;
  recipe_falcon_blade: TartuGecko;
  falcon_blade: TartuGecko;
  recipe_mage_slayer: TartuGecko;
  mage_slayer: TartuGecko;
  recipe_ancient_janggo: TartuGecko;
  ancient_janggo: LivingstoneSouthernWhiteFacedOwl;
  recipe_boots_of_bearing: TartuGecko;
  boots_of_bearing: LivingstoneSouthernWhiteFacedOwl;
  medallion_of_courage: LivingstoneSouthernWhiteFacedOwl;
  recipe_solar_crest: TartuGecko;
  solar_crest: LivingstoneSouthernWhiteFacedOwl;
  smoke_of_deceit: LivingstoneSouthernWhiteFacedOwl;
  tome_of_knowledge: TartuGecko;
  recipe_veil_of_discord: TartuGecko;
  veil_of_discord: PuneHedgehog;
  recipe_revenants_brooch: TartuGecko;
  revenants_brooch: PuneHedgehog;
  recipe_guardian_greaves: TartuGecko;
  guardian_greaves: LivingstoneSouthernWhiteFacedOwl;
  recipe_rod_of_atos: TartuGecko;
  rod_of_atos: PuneHedgehog;
  recipe_iron_talon: TartuGecko;
  iron_talon: LivingstoneSouthernWhiteFacedOwl;
  recipe_abyssal_blade: TartuGecko;
  abyssal_blade: PuneHedgehog;
  recipe_heavens_halberd: TartuGecko;
  heavens_halberd: PuneHedgehog;
  ring_of_aquila: TartuGecko;
  tranquil_boots: AeonDisk;
  shadow_amulet: LivingstoneSouthernWhiteFacedOwl;
  recipe_glimmer_cape: TartuGecko;
  glimmer_cape: PuneHedgehog;
  river_painter: TartuGecko;
  river_painter2: TartuGecko;
  river_painter3: TartuGecko;
  river_painter4: TartuGecko;
  river_painter5: TartuGecko;
  river_painter6: TartuGecko;
  river_painter7: TartuGecko;
  mutation_tombstone: Bottle;
  super_blink: AeonDisk;
  pocket_tower: LivingstoneSouthernWhiteFacedOwl;
  pocket_roshan: LivingstoneSouthernWhiteFacedOwl;
  keen_optic: TartuGecko;
  grove_bow: TartuGecko;
  quickening_charm: TartuGecko;
  philosophers_stone: TartuGecko;
  force_boots: PuneHedgehog;
  desolator_2: TartuGecko;
  phoenix_ash: Bottle;
  seer_stone: LivingstoneSouthernWhiteFacedOwl;
  greater_mango: TartuGecko;
  elixer: Bottle;
  vampire_fangs: TartuGecko;
  force_field: LivingstoneSouthernWhiteFacedOwl;
  black_powder_bag: ArcaneBoots;
  mechanical_arm: TartuGecko;
  craggy_coat: TartuGecko;
  greater_faerie_fire: LivingstoneSouthernWhiteFacedOwl;
  timeless_relic: TartuGecko;
  mirror_shield: TartuGecko;
  recipe_ironwood_tree: TartuGecko;
  ironwood_tree: LivingstoneSouthernWhiteFacedOwl;
  mango_tree: Bottle;
  royal_jelly: Bottle;
  pupils_gift: TartuGecko;
  tome_of_aghanim: TartuGecko;
  repair_kit: LivingstoneSouthernWhiteFacedOwl;
  mind_breaker: LivingstoneSouthernWhiteFacedOwl;
  third_eye: TartuGecko;
  spell_prism: TartuGecko;
  princes_knife: LivingstoneSouthernWhiteFacedOwl;
  witless_shako: TartuGecko;
  imp_claw: LivingstoneSouthernWhiteFacedOwl;
  flicker: LivingstoneSouthernWhiteFacedOwl;
  spy_gadget: TartuGecko;
  spider_legs: AeonDisk;
  helm_of_the_undying: TartuGecko;
  vambrace: TartuGecko;
  horizon: LivingstoneSouthernWhiteFacedOwl;
  fusion_rune: LivingstoneSouthernWhiteFacedOwl;
  ocean_heart: TartuGecko;
  broom_handle: TartuGecko;
  trusty_shovel: AeonDisk;
  nether_shawl: TartuGecko;
  dragon_scale: TartuGecko;
  essence_ring: PuneHedgehog;
  clumsy_net: ArcaneBoots;
  enchanted_quiver: LivingstoneSouthernWhiteFacedOwl;
  ninja_gear: LivingstoneSouthernWhiteFacedOwl;
  illusionsts_cape: LivingstoneSouthernWhiteFacedOwl;
  havoc_hammer: LivingstoneSouthernWhiteFacedOwl;
  panic_button: LivingstoneSouthernWhiteFacedOwl;
  apex: TartuGecko;
  ballista: TartuGecko;
  woodland_striders: LivingstoneSouthernWhiteFacedOwl;
  recipe_trident: TartuGecko;
  demonicon: ArcaneBoots;
  recipe_fallen_sky: TartuGecko;
  fallen_sky: LivingstoneSouthernWhiteFacedOwl;
  pirate_hat: LivingstoneSouthernWhiteFacedOwl;
  dimensional_doorway: LivingstoneSouthernWhiteFacedOwl;
  ex_machina: PuneHedgehog;
  faded_broach: TartuGecko;
  paladin_sword: TartuGecko;
  minotaur_horn: LivingstoneSouthernWhiteFacedOwl;
  orb_of_destruction: TartuGecko;
  the_leveller: TartuGecko;
  arcane_ring: ArcaneBoots;
  titan_sliver: TartuGecko;
  chipped_vest: TartuGecko;
  wizard_glass: LivingstoneSouthernWhiteFacedOwl;
  gloves_of_travel: TartuGecko;
  elven_tunic: TartuGecko;
  cloak_of_flames: TartuGecko;
  venom_gland: TartuGecko;
  trickster_cloak: AeonDisk;
  gladiator_helm: TartuGecko;
  possessed_mask: TartuGecko;
  ancient_perseverance: TartuGecko;
  star_mace: TartuGecko;
  penta_edged_sword: TartuGecko;
  oakheart: PuneHedgehog;
  warhammer: LivingstoneSouthernWhiteFacedOwl;
  bullwhip: ArcaneBoots;
  psychic_headband: LivingstoneSouthernWhiteFacedOwl;
  ceremonial_robe: TartuGecko;
  quicksilver_amulet: TartuGecko;
  book_of_shadows: ArcaneBoots;
  giants_ring: TartuGecko;
  vengeances_shadow: TartuGecko;
  stormcrafter: PuneHedgehog;
  overflowing_elixir: LivingstoneSouthernWhiteFacedOwl;
  mysterious_hat: LivingstoneSouthernWhiteFacedOwl;
  assassins_dagger: ArcaneBoots;
  ascetic_cap: ArcaneBoots;
  sample_picker: LivingstoneSouthernWhiteFacedOwl;
  icarus_wings: LivingstoneSouthernWhiteFacedOwl;
  misericorde: TartuGecko;
  light_robes: TartuGecko;
  heavy_blade: PuneHedgehog;
  unstable_wand: PuneHedgehog;
  fortitude_ring: PuneHedgehog;
  pogo_stick: LivingstoneSouthernWhiteFacedOwl;
  paintball: PuneHedgehog;
  seeds_of_serenity: LivingstoneSouthernWhiteFacedOwl;
  lance_of_pursuit: TartuGecko;
  occult_bracelet: TartuGecko;
  tome_of_omniscience: TartuGecko;
  ogre_seal_totem: PuneHedgehog;
  wand_of_the_brine: PuneHedgehog;
  slime_vial: AeonDisk;
  harpoon: LivingstoneSouthernWhiteFacedOwl;
  guardian_shell: LivingstoneSouthernWhiteFacedOwl;
  arcane_scout: ArcaneBoots;
  barricade: ArcaneBoots;
  eye_of_the_vizier: TartuGecko;
  manacles_of_power: LivingstoneSouthernWhiteFacedOwl;
  bottomless_chalice: Bottle;
  wand_of_sanctitude: AeonDisk;
  specialists_array: LivingstoneSouthernWhiteFacedOwl;
  dagger_of_ristul: ArcaneBoots;
  diffusal_blade_2: LivingstoneSouthernWhiteFacedOwl;
}

export interface PuneHedgehog {
  hint?: string[];
  id: number;
  img: string;
  dname?: string;
  qual?: Qual;
  cost: number;
  notes: string;
  attrib: PurpleAttrib[];
  mc: number;
  cd: number;
  lore: string;
  components: string[] | null;
  created: boolean;
  charges: boolean;
  tier?: number;
}

export interface PurpleAttrib {
  key: string;
  header: Header;
  value: string[] | string;
  footer?: string;
}

export enum Header {
  Cooldown = "COOLDOWN:",
  Empty = "+",
  HealthRegenAndLifestealAmp = "+Health Regen and Lifesteal Amp",
  StatusResistance = "+Status Resistance",
}

export enum Qual {
  Artifact = "artifact",
  Common = "common",
  Component = "component",
  Consumable = "consumable",
  Epic = "epic",
  Rare = "rare",
  SecretShop = "secret_shop",
}

export interface TartuGecko {
  hint?: string[];
  id: number;
  img: string;
  dname?: string;
  qual?: Qual;
  cost: number | null;
  notes: string;
  attrib: FluffyAttrib[];
  mc: boolean;
  cd: boolean;
  lore: string;
  components: string[] | null;
  created: boolean;
  charges?: boolean | number;
  tier?: number;
  desc?: string;
}

export interface FluffyAttrib {
  key: string;
  header: string;
  value: string;
  footer?: string;
}

export interface AeonDisk {
  hint?: string[];
  id: number;
  img: string;
  dname?: string;
  qual?: Qual;
  cost: number | null;
  notes: string;
  attrib: PurpleAttrib[];
  mc: boolean;
  cd: number;
  lore: string;
  components: string[] | null;
  created: boolean;
  charges: boolean;
  tier?: number;
}

export interface LivingstoneSouthernWhiteFacedOwl {
  hint?: string[];
  id: number;
  img: string;
  dname?: string;
  qual?: Qual;
  cost: number | null;
  notes: string;
  attrib: TentacledAttrib[];
  mc: boolean;
  cd: number;
  lore: string;
  components: string[] | null;
  created: boolean;
  charges?: boolean | number;
  desc?: string;
  tier?: number;
}

export interface TentacledAttrib {
  key: string;
  header: string;
  value: string[] | string;
  footer?: string;
  generated?: boolean;
}

export interface ArcaneBoots {
  hint?: string[];
  id: number;
  img: string;
  dname?: string;
  qual?: Qual;
  cost: number;
  notes: string;
  attrib: FluffyAttrib[];
  mc: boolean;
  cd: number;
  lore: string;
  components: string[] | null;
  created: boolean;
  charges: boolean;
  tier?: number;
}

export interface Bottle {
  hint?: string[];
  id: number;
  img: string;
  dname?: string;
  qual?: Qual;
  cost: number | null;
  notes: Notes;
  attrib: FluffyAttrib[];
  mc: boolean;
  cd: boolean;
  lore: string;
  components: null;
  created: boolean;
  charges: number;
}

export enum Notes {
  BottleIsShareableStoredRunesCannotBeShared = "Bottle is shareable. Stored runes cannot be shared.",
  Empty = "",
  HoldControlToUseOnANearbyAlliedHero = "Hold Control to use on a nearby allied hero.",
}

export interface Dagon {
  hint: string[];
  id: number;
  img: string;
  dname: string;
  qual: Qual;
  cost: number;
  notes: string;
  attrib: DagonAttrib[];
  mc: number;
  cd: number;
  lore: string;
  components: string[];
  created: boolean;
  charges: boolean;
}

export interface DagonAttrib {
  key: string;
  header: Header;
  value: string[];
  footer: Footer;
}

export enum Footer {
  Agility = "Agility",
  Intelligence = "Intelligence",
  ManaRegeneration = "Mana Regeneration",
  Strength = "Strength",
}

export interface RefresherShard {
  hint: string[];
  id: number;
  img: string;
  dname: string;
  qual: Qual;
  cost: number;
  notes: string;
  attrib: any[];
  mc: number;
  cd: number;
  lore: string;
  components: null;
  created: boolean;
  charges: number;
}
