// Generated by https://quicktype.io

export interface PopularBuild {
  start_game_items: { [key: string]: number };
  early_game_items: { [key: string]: number };
  mid_game_items: { [key: string]: number };
  late_game_items: { [key: string]: number };
}
